- name: Debian Server Configuration
  hosts: tags_ansible_debian
  vars:
    netbird_setup_key: "{{ lookup('env', 'NETBIRD_SETUP_KEY') }}"
    base_path: /root/ansible

  tasks:
  - name: Install iTerm Shell Integration
    ansible.builtin.script: "{{ base_path }}/files/install_shell_integration.sh"
    args:
      creates: "{{ ansible_env.HOME }}/.iterm2_shell_integration.bash"

  # Install Netbird
  - name: Check to see if /usr/bin/netbird exists
    ansible.builtin.stat:
      path: /usr/bin/netbird
    register: netbird
  - name: Install Netbird when it doesn't already exists
    ansible.builtin.shell: |
      curl -fsSL https://pkgs.netbird.io/install.sh | sh
    when: netbird.stat.executable is not defined
  - name: Netbird UP
    ansible.builtin.shell: "netbird up --setup-key {{ netbird_setup_key }}"
    when: netbird.stat.executable is not defined
   
  - name: Update some basic .profile settings
    ansible.builtin.blockinfile:
      path: "{{ ansible_env.HOME }}/.bashrc"
      block: |
        alias ll='ls -l'
        set -o vi
      marker: '# {mark} ANSIBLE MANAGED BLOCK - aliases'

  - name: Add johnsturgeon imac public ssh key
    ansible.posix.authorized_key:
      user: root
      key: "{{ lookup('env', 'JOHNS_IMAC_PUBLIC_KEY') }}"

  - name: Install useful things
    ansible.builtin.apt:
      name:
        - glances
        - vim
        - jq
      state: latest
      update_cache: yes
