v- name: Debian Server Configuration
  hosts: tags_ansible_debian
  vars:
    netbird_setup_key: "{{ lookup('env', 'NETBIRD_SETUP_KEY') }}"
    netbird_register: true
    base_path: /root/ansible

  tasks:
  - name: Install iTerm Shell Integration
    ansible.builtin.script: "{{ base_path }}/files/install_shell_integration.sh"
    args:
      creates: "{{ ansible_env.HOME }}/.iterm2_shell_integration.bash"

  - name: Update some basic .profile settings
    ansible.builtin.blockinfile:
      path: "{{ ansible_env.HOME }}/.bashrc"
      block: |
        alias ll='ls -l'
        set -o vi
      marker: '# {mark} ANSIBLE MANAGED BLOCK - aliases'

  - name: Add johnsturgeon imac public ssh key
    ansible.posix.authorized_key:
      user: root
      key: "{{ lookup('env', 'JOHNS_IMAC_PUBLIC_KEY') }}"
      
  - name: Check for netbird setup key
    ansible.builtin.fail:
      msg: "netbird_setup_key is required"
    when: netbird_setup_key is not defined

  - name: Install Netbird
    ansible.builtin.include_role:
      name: netbird

  - name: Check Netbird Status
    ansible.builtin.shell: |
      netbird status --detail
