- name: Debian Server Configuration
  hosts: tags_ansible_debian
  vars:
    base_path: /root/ansible

  tasks:
  - name: Install iTerm Shell Integration
    ansible.builtin.script: "{{ base_path }}/files/install_shell_integration.sh"
    args:
      creates: "{{ ansible_env.HOME }}/.iterm2_shell_integration.bash"

  - name: Update some basic .profile settings
    ansible.builtin.blockinfile:
      path: "{{ ansible_env.HOME }}/.bashrc"
      block: |
        alias ll='ls -l'
        set -o vi
      marker: '# {mark} ANSIBLE MANAGED BLOCK - aliases'

  - name: Add johnsturgeon imac public ssh key
    ansible.posix.authorized_key:
      user: root
      key: "{{ lookup('community.general.onepassword', 'JOHNS_IMAC_PUBLIC_KEY', vault='HomelabSecrets') }}"

  - name: Remove "prometheus-node-exporter-*" package
    ansible.builtin.apt:
      name: 
        - prometheus-node-exporter-collectors
        - prometheus-node-exporter
      state: absent
  
  - name: Install useful things
    ansible.builtin.apt:
      name:
        - glances
        - vim
        - jq
      state: latest
      update_cache: yes
